In [2]:
import pandas as pd

df = pd.read_csv("../data/X_raw.csv")
print(df.iloc[0].to_dict())

{'request_count': 1.0, 'unique_ips': 1.0, 'avg_response_time': 153.0, 'median_response_time': 153.0, 'p95_response_time': 153.0, 'p99_response_time': 153.0, 'max_response_time': 153.0, 'std_response_time': 0.0, 'error_rate_5xx': 0.0, 'error_rate_4xx': 0.0, 'success_rate': 1.0, 'avg_bytes_sent': 2256.0, 'total_bytes_sent': 2256.0, 'bot_ratio': 1.0, 'mobile_ratio': 0.0, 'desktop_ratio': 0.0, 'api_ratio': 1.0, 'static_ratio': 0.0, 'auth_ratio': 0.0, 'get_ratio': 1.0, 'post_ratio': 0.0, 'hour': 0.0, 'is_weekend': 0.0, 'is_business_hours': 0.0, 'response_time_change': 0.0, 'request_count_change': 0.0, 'error_rate_change': 0.0, 'rolling_avg_response': 153.0, 'response_vs_rolling': 0.0, 'stress_score': 153.0, 'quality_degradation': 151.4851485148515, 'latency_spike': 0.0, 'error_severity_ratio': 0.0, 'response_cv': 0.0, 'load_pressure': 153.0, 'log_avg_response': 5.0369526024136295, 'log_p99_response': 5.0369526024136295, 'log_std_response': 0.0, 'log_load_pressure': 5.0369526024136295, 'response_vs_rolling_abs': 0.0, 'response_zscore_per_server': -0.0816488729249575, 'severity_latency': -0.898, 'severity_error': -1.0, 'severity_traffic': -0.5557000000000001, 'max_severity': -0.5557000000000001, 'combined_severity': 0.0}

In [4]:
import pandas as pd
import json

df = pd.read_csv("../data/X_raw.csv")

row = df.iloc[0].to_dict()

print(json.dumps(row, indent=2))

{
  "request_count": 1.0,
  "unique_ips": 1.0,
  "avg_response_time": 153.0,
  "median_response_time": 153.0,
  "p95_response_time": 153.0,
  "p99_response_time": 153.0,
  "max_response_time": 153.0,
  "std_response_time": 0.0,
  "error_rate_5xx": 0.0,
  "error_rate_4xx": 0.0,
  "success_rate": 1.0,
  "avg_bytes_sent": 2256.0,
  "total_bytes_sent": 2256.0,
  "bot_ratio": 1.0,
  "mobile_ratio": 0.0,
  "desktop_ratio": 0.0,
  "api_ratio": 1.0,
  "static_ratio": 0.0,
  "auth_ratio": 0.0,
  "get_ratio": 1.0,
  "post_ratio": 0.0,
  "hour": 0.0,
  "is_weekend": 0.0,
  "is_business_hours": 0.0,
  "response_time_change": 0.0,
  "request_count_change": 0.0,
  "error_rate_change": 0.0,
  "rolling_avg_response": 153.0,
  "response_vs_rolling": 0.0,
  "stress_score": 153.0,
  "quality_degradation": 151.4851485148515,
  "latency_spike": 0.0,
  "error_severity_ratio": 0.0,
  "response_cv": 0.0,
  "load_pressure": 153.0,
  "log_avg_response": 5.0369526024136295,
  "log_p99_response": 5.0369526024136295,
  "log_std_response": 0.0,
  "log_load_pressure": 5.0369526024136295,
  "response_vs_rolling_abs": 0.0,
  "response_zscore_per_server": -0.0816488729249575,
  "severity_latency": -0.898,
  "severity_error": -1.0,
  "severity_traffic": -0.5557000000000001,
  "max_severity": -0.5557000000000001,
  "combined_severity": 0.0
}

In [7]:
df.tail(5)

,request_count,unique_ips,avg_response_time,median_response_time,p95_response_time,p99_response_time,max_response_time,std_response_time,error_rate_5xx,error_rate_4xx,...,log_p99_response,log_std_response,log_load_pressure,response_vs_rolling_abs,response_zscore_per_server,severity_latency,severity_error,severity_traffic,max_severity,combined_severity
4438,1.0,1.0,86.0,86.0,86.0,86.0,86.0,0.0,0.0,0.0,...,4.465908,0.0,4.465908,43.333333,-0.329212,-0.942667,-1.0,-0.5557,-0.5557,0.0
4439,1.0,1.0,79.0,79.0,79.0,79.0,79.0,0.0,0.0,0.0,...,4.382027,0.0,4.382027,103.666667,-0.340705,-0.947333,-1.0,-0.5557,-0.5557,0.0
4440,1.0,1.0,228.0,228.0,228.0,228.0,228.0,0.0,0.0,1.0,...,5.433722,0.0,5.433722,58.333333,0.180908,-0.848000,-1.0,-0.5557,-0.5557,0.0
4441,1.0,1.0,543.0,543.0,543.0,543.0,543.0,0.0,0.0,0.0,...,6.298949,0.0,6.298949,319.777778,1.177568,-0.638000,-1.0,-0.5557,-0.5557,0.0
4442,1.0,1.0,171.0,171.0,171.0,171.0,171.0,0.0,0.0,0.0,...,5.147494,0.0,5.147494,73.000000,-0.036688,-0.886000,-1.0,-0.5557,-0.5557,0.0

In [8]:
df.sample(5)

,request_count,unique_ips,avg_response_time,median_response_time,p95_response_time,p99_response_time,max_response_time,std_response_time,error_rate_5xx,error_rate_4xx,...,log_p99_response,log_std_response,log_load_pressure,response_vs_rolling_abs,response_zscore_per_server,severity_latency,severity_error,severity_traffic,max_severity,combined_severity
2455,1.0,1.0,51.0,51.0,51.0,51.00,51.0,0.000000,0.0,0.0,...,3.951244,0.000000,3.951244,41.333333,-0.428383,-0.966000,-1.0,-0.5557,-0.5557,0.0
221,1.0,1.0,116.0,116.0,116.0,116.00,116.0,0.000000,0.0,1.0,...,4.762174,0.000000,4.762174,35.833333,-0.225367,-0.922667,-1.0,-0.5557,-0.5557,0.0
1561,1.0,1.0,232.0,232.0,232.0,232.00,232.0,0.000000,0.0,1.0,...,5.451038,0.000000,5.451038,52.333333,0.194911,-0.845333,-1.0,-0.5557,-0.5557,0.0
4039,2.0,2.0,47.0,47.0,47.9,47.98,48.0,1.414214,0.0,0.0,...,3.891412,0.881374,4.553877,5.666667,-0.464210,-0.968067,-1.0,-0.1114,-0.1114,0.0
3701,1.0,1.0,112.0,112.0,112.0,112.00,112.0,0.000000,0.0,0.0,...,4.727388,0.000000,4.727388,31.500000,-0.229272,-0.925333,-1.0,-0.5557,-0.5557,0.0